-- MySQL Script generated by MySQL Workbench
-- Sun Nov 16 10:15:33 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wcms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wcms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wcms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wcms` ;

-- -----------------------------------------------------
-- Table `wcms`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wcms`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(80) NULL,
  `user_pass` CHAR(40) NULL,
  `user_first_name` VARCHAR(255) NULL,
  `user_last_name` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wcms`.`uploads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wcms`.`uploads` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `upload_name` TEXT NULL,
  `upload_file_name` TEXT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wcms`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wcms`.`posts` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `post_author` INT NOT NULL,
  `post_image` INT NULL,
  `post_type` VARCHAR(20) NULL,
  `post_title` TEXT NULL,
  `post_date` DATETIME NULL,
  `post_content` LONGTEXT NULL,
  `post_excerpt` TEXT NULL,
  `post_status` CHAR(2) NULL,
  `post_order` INT NULL,
  PRIMARY KEY (`ID`, `post_author`),
  INDEX `fk_posts_users_idx` (`post_author` ASC),
  INDEX `fk_posts_uploads1_idx` (`post_image` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`post_author`)
    REFERENCES `wcms`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_uploads1`
    FOREIGN KEY (`post_image`)
    REFERENCES `wcms`.`uploads` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wcms`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wcms`.`categories` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(255) NULL,
  `cat_description` TEXT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wcms`.`post_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wcms`.`post_categories` (
  `posts_categories_ID` INT NOT NULL AUTO_INCREMENT,
  `posts_ID` INT NOT NULL,
  `categories_ID` INT NOT NULL,
  PRIMARY KEY (`posts_categories_ID`, `posts_ID`, `categories_ID`),
  INDEX `fk_posts_has_categories_categories1_idx` (`categories_ID` ASC),
  INDEX `fk_posts_has_categories_posts1_idx` (`posts_ID` ASC),
  CONSTRAINT `fk_posts_has_categories_posts1`
    FOREIGN KEY (`posts_ID`)
    REFERENCES `wcms`.`posts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_categories_categories1`
    FOREIGN KEY (`categories_ID`)
    REFERENCES `wcms`.`categories` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `users` (`ID`, `user_email`, `user_pass`, `user_first_name`, `user_last_name`) VALUES
(5, 'nicholas@iotecnologia.com.br', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220', 'NÃ­cholas', 'AndrÃ©'),
(12, 'rosana@gmail.com', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 'Rosana', 'Alves');

